### ISSUE TITLE
Lock version of critical apps

### ISSUE THREAD

**Issue by SchnWalter** [mission-impossible-android/mission-impossible-android#107]
There were some recent changes on [Orbot](https://f-droid.org/repository/browse/?fdid=org.torproject.android) that basically makes it crash on startup. We should evaluate what version we should use, and lock the version. And maybe do the same for other apps.

**Comment by patcon** [comment]
@cjeanneret any idea what this might be?

Here's the config we use, fwiw:
https://github.com/mission-impossible-android/mission-impossible-android/blob/master/mia/templates/mia-default/archive/data/data/org.ethack.orwall/shared_prefs/org.ethack.orwall_preferences.xml

**Comment by SchnWalter** [comment]
I believe it has nothing to do with the settings file. It could not hlfind an audio file.

I was using the 15.0.1-RC-3-PIE build from F-Droid. And it worked perfectly once I reverted to 14.1.4-PIE.

**Comment by SchnWalter** [comment]
I have locked the version in https://github.com/mission-impossible-android/mission-impossible-android/commit/b805070f0a8160b35d063f89f7c2df6f43c23cd8

We can unlock it once things are working properly.
