### ISSUE TITLE
Checksums of APKs and mia-update.zip

### ISSUE THREAD

**Issue by SchnWalter** [mission-impossible-android/mission-impossible-android#31]
We should also support/require checksums of APK files that are locked on a particular version. And also for other files downloaded directly from the internet.

**Comment by patcon** [comment]
You thinking we should store hashes in the lockfile for apps? We could technically store them as files in the cache, but things in the cache would be odd to version-control, whereas a lockfile would make sense

**Comment by SchnWalter** [comment]
Fixed in PR #100

**Comment by patcon** [comment]
Nice!
