### ISSUE TITLE
Fix error from hardcoded assumption of python package

### ISSUE THREAD

**Issue by patcon** [mission-impossible-android/mission-impossible-android#77]
https://gist.github.com/patcon/9aeb2d39c16d41f63554

We need to figure out how to not depend on this stuff:
https://github.com/mission-impossible-android/mission-impossible-android/blob/master/mia/commands/definition.py#L36

Any thoughts @SchnWalter? Not exactly sure how this packaging thing works :)

**Comment by SchnWalter** [comment]
Looks like the `/mia.egg-info` folder is needed for the pkg_resources to work. I'll try to find another way for the `/tools/mia` script to work without it, since it is not recommended to add it to version control.
