### ISSUE TITLE
Go back to mirroring package directory structure in templates/definitions

### ISSUE THREAD

**Issue by patcon** [mission-impossible-android/mission-impossible-android#78]
While sorting out https://github.com/mission-impossible-android/mission-impossible-android/issues/33, realized that mike's `mia definition update-from-template` would be really helpful in keeping the noise down in template versions.

For example, the `wifi-only` template that I was working on could be a minimal skeleton, and creating a definition from it would be:

```
mia definition create mako-wifi --template=mia-default
mia definition update-from-template mako-wifi --template=wifi-only
```

We could make that process smoother, but it essentially means we copy a base, then copy into the definition any exceptions from the next template, so they sit on top or override. We can definition improve on that, but it opens up the needed options for now, so I can get working on other templates without borking the stuff in the default (for people who don't want their radio killed :)

**Comment by SchnWalter** [comment]
We most probably don't want the definition README.md in the built mia-update.zip file.

Are you OK with changing the current version of settings file in order to add an extra entry for excluding files and directories? Something like:
```
excluded: list(str())
```

**Comment by patcon** [comment]
Heyo @SchnWalter! I don't personally think it's necessary, but hear me out and let me know what you think!

I don't think we need an `excluded` flag as you explained it, as we probably should *not* be operating such that the template root is the zip archive root, but rather having a subdir where the zip archive skeleton exists. This latter approach was kinda what we were [doing with the `pkg/` subdir](https://github.com/mission-impossible-android/mission-impossible-android/tree/d9648b2e9acf58ba01f97e7c8d5090a27b909b68), back before we had the awesome template feature, and it worked really well.

Thinking the way forward would be for each template to have the template root as a scratch space that doesn't go into an archive (things like settings.yaml and the readme), and a subdir (maybe called `archive/` or whatever?) where the files that go into the zip archive live. This would allow us to make use of a `parent_template` key in `settings.yaml`, so when we build a definition, we could find the "most" parent template by tracing back through each `settings.yaml`, then `cp -r` back through each `archive/` dir for child templates to generate the build artifact that gets zipped up. So via a simple copy of the directory structures, we get inheritance of files and stuff from parent templates, and children can override by placing their own file. The thought was that the parental yaml would be inherited as well.

Here's an example layout of how I was planning to do it, but I'm definitely all ears:

```
/tmp/mia-layout  ᐅ tree
.
└── templates
    ├── mia-default
    │   ├── README.md
    │   ├── archive
    │   │   ├── META-INF
    │   │   │   └── com
    │   │   │       └── google
    │   │   │           └── android
    │   │   │               └── updater-script
    │   │   ├── data
    │   │   │   └── data
    │   │   │       └── com.android.inputmethod.latin
    │   │   │           └── shared_prefs
    │   │   │               └── com.android.inputmethod.latin_preferences.xml
    │   │   └── system
    │   │       ├── etc
    │   │       │   └── init.d
    │   │       │       ├── 91firewall
    │   │       │       └── Y02firstboot
    │   │       └── lib
    │   │           └── libjni_unbundled_latinimegoogle.so
    │   └── settings.yaml
    └── wifi-only
        └── archive
            ├── META-INF
            │   └── com
            │       └── google
            │           └── android
            │               └── updater-script
            ├── README.md
            └── settings.yaml    # contains a `parent_template: mia-default` key
```

So in the above, the `wifi-only` template has a ['parent_template` key](https://github.com/mission-impossible-android/mission-impossible-android/blob/master/docs/target.settings.yaml#L7) among other things, and the `mia-default` template has no `parent_template` key. So when generating definition from `wifi-only`, that definition (say `myphone`) would `parent_template: wifi-only`, and so would build a archive by copying in `mia-default`'s archive dir, then copying `wifi-only`'s archive dir on top, and then copying anything custom to the definition.

Is that crazy?? :)

**Comment by SchnWalter** [comment]
`archive` -- sounds good to me!

By "the parental yaml would be inherited" you mean: have the settings.yaml of the top most parent, then merge in the changes from the 2nd one and so on, right?

Let's hope this will be only an additive process.

**Comment by patcon** [comment]
> Let's hope this will be only an additive process.

Good call. If we have a practical use-case where we need to remove a key, yaml null keys would probably work more obviously. Anyhow, can cross that when we come to it, I suppose -- premature optimization is the devil :)
