### ISSUE TITLE
Install AdAway? (Google has gone to far...)

### ISSUE THREAD

**Issue by SchnWalter** [mission-impossible-android/mission-impossible-android#79]
I would like to keep non-tracking adds, after all that is the busyness mode of the internet these days, but I'm not sure there is such a thing as non-tracking adds...

And this time has gone to far, I was reading news in Orfox on my CM built with MIA, and then i saw this: "Google Ads wants to read your contacts, allow?" - https://twitter.com/SchnWalter/status/588793072965787649 

I would suggest dealing with this kind of things with some external scripts blocker like https://github.com/sufficientlysecure/ad-away -- maybe have it as a separate template that can be used to update any other template, or just as an extra entry in the apps list?

**Comment by patcon** [comment]
This is a great idea btw! I've been meaning to dig into ad-away, but no personal experience yet

**Comment by SchnWalter** [comment]
I've been using AdAway on my main phone for a couple of months now, seems to be working just as advertised.

But for the "XXX wants to read your contacts, allow?" maybe we should talk to the GuardianProject guys to make sure it is disabled in Orfox.

**Comment by patcon** [comment]
Openned the above issue in their queue

**Comment by SchnWalter** [comment]
Forgot to mention that AdAway is not playing nice with OrWall.  Both applications need to change the system proxy settings in order to work.
