### ISSUE TITLE
Update UI after changing airplane mode status

### ISSUE THREAD

**Issue by SchnWalter** [mission-impossible-android/mission-impossible-android#94]
In [/data/.firstboot.sh](https://github.com/mission-impossible-android/mission-impossible-android/blob/master/mia/templates/mia-default/other/firstboot.sh#L81) we enable airplane mode by default... but the UI does not update to reflect the change.

I've tested `settings put global airplane_mode_on 1` on a running system, and it did not even close an active Bluetooth connection. Then I've searched the webs and [found](https://developer.android.com/reference/android/content/Intent.html#ACTION_AIRPLANE_MODE_CHANGED) that you need to [broadcast](http://muzso.hu/2014/04/02/how-to-programmatically-enable-and-disable-airplane-flight-mode-on-android-4.2) the event/intent, the DB is not watched for changes. (Maybe we should make sure that all updated settings are taken into account at first boot.)

```
settings put global airplane_mode_on 1
am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true
```

Didn't get to test if it is actually working inside `.firstboot.sh`.

**Comment by patcon** [comment]
:+1:

**Comment by SchnWalter** [comment]
For some reason the airplane mode is not enabled at all for me from within the firstboot script... using:
```
# GH-94: Enable Airplane Mode and broadcast the event.
/system/bin/settings put global airplane_mode_on 1
/system/bin/am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true
```

I think I'm going to start adding logs for all things inside the firstboot script, and log also the response codes.

**Comment by patcon** [comment]
> I think I'm going to start adding logs for all things inside the firstboot script, and log also the response codes.

Great idea. I'll aim to rewipe soon and see if I'm seeing the same thing. Will update
